### ISSUE TITLE
Skydome

### ISSUE THREAD

**Issue by DvanLaar** [DvanLaar/Grafisch#11]
Add a textured skydome, make it HDR for an additional 1 pt.

**Comment by ludopulles** [comment]
@jeverink is het nu ook al HDR?

**Comment by jeverink** [comment]
De kleuren worden opgeslagen als floats en kunnen dus boven de 1f komen, maar de texture die word ingeladen geeft altijd kleuren tussen de 0f en 1f.  Dus als je een HDR texture wil zou je special textures moeten inladen. (Bijvoorbeeld die van [hier](http://www.pauldebevec.com/Probes/) , maar voor deze moet je ook andere code voor het samplen gebruiken, maar die staat er bij die website wel bijgegeven.)
