### ISSUE TITLE
Camera

### ISSUE THREAD

**Issue by DvanLaar** [DvanLaar/Grafisch#3]
- [ ] Your camera must support an arbitrary field of view. It must be possible to set FOV from the application, using an angle in degrees

- [ ] The camera must support arbitrary positions and orientations. It must be possible to aim the camera based on an arbitrary 3D position and target

**Comment by ludopulles** [comment]
Opzich ben ik hier wel ongeveer klaar mee.
Nog twee dingen:

- [ ] Ze willen dat de FOV in graden (noem dit `theta`) gespecificeerd kan worden, dan is nu `tan(FOV) = theta`.
- [ ] De camera moet zich op een bepaald punt kunnen richten. Dit kan door de rotation te resetten. ~Ik maak gebruik van quaternions, dus moet je een `q` vinden zodanig dat `q  * (0,0,-1f) = dir`, waarbij `dir` de relatieve richting vanuit de camera is. Ik vermoed, dat dit als oplossing geeft: `q = dir * (0, 0, 1f)`.~

Mijn vraag aan jullie is, hoe willen we deze input van de gebruiker vragen?

**Comment by ludopulles** [comment]
Blijkt uit `slack` dat deze input volstaat door keyboard input te vragen.
